### ISSUE TITLE
Clarification on cbl beta migration

### ISSUE THREAD

**Issue by natgross** [cbl-dart/cbl-dart#277]
Am a little confused with the various pkg's currently out there and with the migration notice.
Currently I have the following in my pubspec.
`
  cbl: ^1.0.0-beta.11

  cbl_flutter: ^1.0.0-beta.10

  cbl_flutter_ce: ^1.0.0-beta.4 # Couchbase Lite Community Edition.
`
What should be my migration path?
Thanks.

**Comment by blaugold** [comment]
Sorry for the confusion 😅 

You should just be able to upgrade the packages to the latest beta version, which currently are:
```
cbl: ^1.0.0-beta.13
cbl_flutter: ^1.0.0-beta.11
cbl_flutter_ce: ^1.0.0-beta.5
```

There was a breaking change in [`cbl: 1.0.0-beta.12`](https://github.com/cbl-dart/cbl-dart/commit/ec5d1931a65e5dc569c9e5f8da26a5235afdd4f8) but only if you were using `Blob.fromStream`.

The migration notice is for users of the `0.x.x` versions because those aren't updated anymore.
The plan for a stable `1.0.0` release is the end of February.

**Comment by natgross** [comment]
The thing that has me confused is this pkg (which you published at the same time as the others):
**cbl_dart: ^1.0.0-beta.4**

What is this all about?
Thanks.

**Comment by blaugold** [comment]
You need to use `cbl_dart` if you want to use Couchbase Lite in pure Dart apps, like servers or CLIs. 
It's also useful in the context of Flutter apps because it allows you to use Couchbase Lite in [Flutter unit tests](https://pub.dev/packages/cbl_flutter/versions/1.0.0-beta.11#-flutter-unit-tests).

**Comment by natgross** [comment]
It seems to me that cbl and cbl_dart should be [migrated into] one pkg for pure Dart apps.

**Comment by blaugold** [comment]
Each version of `cbl_dart` distributes a specific version of the native libraries. Keeping `cbl` and `cbl_dart` as separate packages allows for some extra flexibility.

But having fewer packages would also be good, and they might get merged in the future.

**Comment by natgross** [comment]
Until the merge, please document at the top (of the doc file) that if you are doing X, use cbl, if you are doing Y, use cbl_dart. 
This simple request is a bit tricky. Not so simple to document. 
That's the point.
Anyhow, thanks for listening. You can close this issue out.

**Comment by blaugold** [comment]
Thanks for the feedback! I've opened #281, to track improving the docs regarding this.
