### ISSUE TITLE
Release build apk size

### ISSUE THREAD

**Issue by function1983** [cbl-dart/cbl-dart#388]
**Describe the bug**

This is not a bug, rather concerning the app's release apk size. I have been using couchbase_lite. Now that I wanted to try cbl-flutter as a drop in replacement, the app still function as expected but apk size (without much code change) jumped from 23MB to 41MB. Is this expected behavior or did I miss some key configurations here? Right now I only use cbl-flutter for android and iOS, but soon I will try to implement on desktop environments as well. Thank you.

**To Reproduce**

1. `flutter build apk` in terminal

**Expected behavior**

Modestly increase in apk size

**Screenshots**

**Environment (please complete the following information):**

 - OS:
 ```
  cbl: ^2.0.0+0
  cbl_flutter: ^2.0.0
  cbl_flutter_ce: ^2.0.0
```

**Additional context**

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-52-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

**Comment by blaugold** [comment]
An increase of ~20 MB is to be expected, but it's not as bad as it seems. The Couchbase Lite binaries are ~5 MB for each supported architecture, and APKs are built to run on 4 architectures. 

When submitting an app to the Play Store as an app bundle, multiple versions of the app are created for distribution. These versions are architecture-specific and will only contain the binaries for one architecture.

**Comment by blaugold** [comment]
Actually, I just looked into android app sizes a bit, and it turns out for Android the size of the binaries is around 16 MB. I confused them with the binaries for iOS, which are quite a bit smaller. I am not sure why. Android is definitely an outlier in terms of binaries sizes compared to other platforms.

When building an Android app for the arm architecture only, an empty Flutter app is ~5 MB, and when `cbl` is added it is ~21 MB.

To better understand what is going on, you could run `flutter build apk --target-platform android-arm --analyze-size` to analyze the size of the app.

**Comment by blaugold** [comment]
Another update: The 16 MB that are reported when analyzing the app size with the Flutter dev tools are of the compressed binaries. Uncompressed, the binaries are ~50 MB, which means that the Android Gradle Plugin is not stripping debug symbols from native binaries as it should. Someone has already [filed a bug](https://issuetracker.google.com/issues/237187538) for this.

This should not be a blocker though when deploying to the Play Store through app bundles because debug symbols get stripped in the release process.

**Comment by function1983** [comment]
My apology. You are absolutely right. Since I usually build release bundle and forgot to target arm64 when test build apk it does include all other architectures. With --target-platform android-arm64 flag on, the size is 26.2MB (a 10% increase from from 23MB) which I think is much more acceptable (libcblite.so is 14.6MB and libcblitedart.so is 730KB).
