### ISSUE TITLE
Crash on iOS with 2.1.8

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#472]
Hi :)

**Describe the bug**

currently, we face some fatal crash with the latest release under iOS as soon as the replicator listener gets added. We still use an older Flutter version, as we also run into some fatal crashes with cbl 2.1.7 & Flutter 3.7.7 and we hadn't time to debug it, yet.  I hope the stack trace I've attached offers enough information. Please let me know if you need more information.

**Stacktrace**

[4a3b1280d35649b3aeeca55d1475f24a-symbolicated.log](https://github.com/cbl-dart/cbl-dart/files/11094100/4a3b1280d35649b3aeeca55d1475f24a-symbolicated.log)

**Environment (please complete the following information):**

 - OS: iOS
 - Flutter: 3.7.5
 - `cbl`: 2.1.8
 - `cbl_flutter`: 2.0.6
 - `cbl_flutter_ce`: 2.1.7

**Comment by blaugold** [comment]
Hey @nblum37, there has been an unfortunate bug in the Dart SDK that was released with Flutter 3.7.0, that lead to the crash that you are seeing. I was able to implement a workaround in `cbl` 2.1.5, but now with Flutter 3.7.8, a fix for the bug has landed that inverts the workaround in `cbl`. `cbl` 2.1.8 removes the workaround so that it works again with Flutter >=3.7.8.

**Comment by nblum37** [comment]
Ok, thanks for the explanation.
