### ISSUE TITLE
Pull replicator get stuck at busy state with SGW 3.1

### ISSUE THREAD

**Issue by nblum37** [cbl-dart/cbl-dart#493]
**Describe the bug**

Since one week we run into an issue, that some of the documents are not synced anymore. This seems to be correlated with an upgrade of the SGW from 3.0.4 to 3.1.0. I don't really think, it is something, that can be fixed on the CBL side, however, I guess understanding the CBL-side better will help to find the actual issue. Thank you for your support!

**To Reproduce (within our SGW setup)**

1. Open the replicator and wait until it reaches 100% progress
2. However, there are still some of the latest documents missing, and the pull replicator still has the state busy
3. Reconnect the replicator
4. The replicator will directly jump to a certain percentage (65% in the attached example) progress and state busy for time >15min
5. Pushing documents is still possible and also the heartbeat is still active. The missing document would be available at the SGW e.g. via the changes feed. No visible errors in the SGW logs.

**Log files**

[stuck_pull_replicator.zip](https://github.com/cbl-dart/cbl-dart/files/11740209/stuck_pull_replicator.zip)

**Environment (please complete the following information):**
 - OS: Android & iOS
 - `cbl`: 2.1.9
 - `cbl_flutter`: 2.0.7
 - `cbl_flutter_ce`: 2.2.0
 - SGW: 3.1.0

**Comment by nblum37** [comment]
After two days of debugging, we found the reason: Some documents contained the `_rev` key as data instead of a meta key. After deleting all documents containing this issue, everything seems to work fine again. Even though the `_rev` key is of course reserved for special use, I would expect a more robust error handling. Should I close this issue and re-create a new one at the CB forum? Or is there also something CBL can improve?

**Comment by nblum37** [comment]
This issue is related to
https://www.couchbase.com/forums/t/documents-not-syncing-to-mobile-clients-with-reserved-internal-property-rev-after-upgrade-to-3-1-0/36548

**Comment by blaugold** [comment]
@nblum37 Sorry for not responding earlier.

Looking at the information in the Couchbase Forum post, my intuition is that it is a bug in Sync Gateway 3.1.0, since the issue started happening after upgrading the Sync Gateway.

Also, as far as I understand it, the `_rev` key is never observed in Couchbase Lite. Not in documents/data loaded from the database, nor logs. Is that correct?

The post in the CB forum is the right place to bring the Sync Gateway team's attention to the problem, but let's leave this issue open until it's definitely resolved.

**Comment by blaugold** [comment]
> Also, as far as I understand it, the _rev key is never observed in Couchbase Lite. Not in documents/data loaded from the database, nor logs. Is that correct?

I just looked at the logs provided in this issue and noticed `_env` in the changes coming from the Sync Gateway. For example:

```
21:27:08.896949| [BLIPMessages]: RECEIVED: REQ #68 NZ {
	rev: 3-b16a0738c75e4e7dd4a75268985bfddb
	sequence: "11017463:9467159"
	history: 2-16a652088335051a2d707ac78cbed6ee,1-565c2193ac14e50122cba59d78fd77a83a5be42e
	Content-Type: application/json
	Profile: rev
	id: bb55eb29-355f-49bf-9b44-f49aca6e3421
	BODY: {"_rev":"1-565c2193ac14e50122cba59d78fd77a83a5be42e",...
```

What is interesting here is that the `_rev` in the body contains an old revision ID, not the current one.

In every instance where the body sent from the Sync Gateway contains `_rev` the revision ID starts with 1, so it's always the ID of the first document revision. The revision ID you shared in the CB forum from the document in Couchbase Server also starts with 1. Can you recall instances where this is not the case? That might be a pointer to root cause of the bug.

**Comment by nblum37** [comment]
Thanks for the input! What we also observed, even though _rev is within the body (sometimes) according to the BLIPMessage, it is not visible in the CBL document's body, when retrieving the document from the database. It also seems like, if the real `rev` and the `_rev` value in the body is equal, there are no syncing issues. I had no time, yet, to check if the issue occurs as soon as both differ. Currently, the unwanted `_rev` in the body occurs at around 20% of all created documents

**Comment by nblum37** [comment]
I would close the issue for now as the source of the _rev entries was detected on the server side. The reason why it breaks the synchronization process is still unknown. Thanks for the feedback!
